run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Smooth");
run("Find Edges");
run("Adapative3DThreshold ", "base=20 mask=1 local=1");
//setThreshold(1, 255);
setOption("BlackBackground", false);
run("Make Binary", "thresholded remaining black");
run("Dilate");
run("Close-");
run("Close-");
run("Close-");
